server:
  port: 9091
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: postgres
    password: 55555
    url: jdbc:postgresql://localhost:5432/polardb
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
    default-schema: public
logging:
  level:
    liquibase: DEBUG

polar:
  greeting: Welcome to the local book catalog!